[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # Questo è cruciale per la compilazione WebAssembly

[dependencies]
wasm-bindgen = "0.2" # Permette l'interoperabilità tra Rust e JavaScript
web-sys = { version = "0.3", features = ["console"] }

